services:
  movie-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./MovieApi/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MovieApiContext=Server=sqlserver,1433;Database=MovieApi;User Id=sa;Password=${DOCKER_SQL_PASSWORD};TrustServerCertificate=true;
      - VERCEL_BLOB_TOKEN=${VERCEL_BLOB_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./MovieApi/.env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DOCKER_SQL_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -C -No -S localhost -U sa -P ${DOCKER_SQL_PASSWORD} -Q 'SELECT 1'"
        ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

volumes:
  sqlserver-data:
